import type { Skill } from "@/components/skills/types"

export const list: Skill[] = [ // should ideally be getting these from an api
    { id: "html", name: "HTML", category: "Frontend" },
    { id: "css", name: "CSS", category: "Frontend" },
    { id: "javascript", name: "JavaScript", category: "Frontend" },
    { id: "typescript", name: "TypeScript", category: "Frontend" },
    { id: "react", name: "React", category: "Frontend" },
    { id: "nextjs", name: "Next.js", category: "Frontend" },
    { id: "vue", name: "Vue.js", category: "Frontend" },
    { id: "angular", name: "Angular", category: "Frontend" },
    { id: "svelte", name: "Svelte", category: "Frontend" },
    { id: "tailwind", name: "Tailwind CSS", category: "Frontend" },
    { id: "nodejs", name: "Node.js", category: "Backend" },
    { id: "python", name: "Python", category: "Backend" },
    { id: "java", name: "Java", category: "Backend" },
    { id: "csharp", name: "C#", category: "Backend" },
    { id: "php", name: "PHP", category: "Backend" },
    { id: "golang", name: "Go", category: "Backend" },
    { id: "rust", name: "Rust", category: "Backend" },
    { id: "ruby", name: "Ruby", category: "Backend" },
    { id: "mysql", name: "MySQL", category: "Database" },
    { id: "postgresql", name: "PostgreSQL", category: "Database" },
    { id: "mongodb", name: "MongoDB", category: "Database" },
    { id: "redis", name: "Redis", category: "Database" },
    { id: "sqlite", name: "SQLite", category: "Database" },
    { id: "docker", name: "Docker", category: "DevOps" },
    { id: "kubernetes", name: "Kubernetes", category: "DevOps" },
    { id: "aws", name: "AWS", category: "DevOps" },
    { id: "azure", name: "Azure", category: "DevOps" },
    { id: "gcp", name: "Google Cloud", category: "DevOps" },
    { id: "git", name: "Git", category: "DevOps" },
    { id: "react-native", name: "React Native", category: "Mobile" },
    { id: "flutter", name: "Flutter", category: "Mobile" },
    { id: "swift", name: "Swift", category: "Mobile" },
    { id: "kotlin", name: "Kotlin", category: "Mobile" },
]